name: Go

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'

#      # 標準ライブラリのみでビルドできるので今はまだ不要
#      - name: Tidy and verify module dependencies
#        run: |
#          go mod tidy
#          go mod verify

      - name: Test
        run: go test -v -cover ./internal/...
